/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pathfinder;

import org.junit.Test;
import static org.junit.Assert.*;
import pathfinder.model.Grid;
import pathfinder.model.ArrayCoordinate;

public class AppTest {
    @Test public void Test1() {
        Grid g = new Grid("Easy");
        ArrayCoordinate point1 = new ArrayCoordinate(0, 0);
        g.setPreviousButton(point1);
        assertTrue(g.isAdjacent(0, 1));
        assertFalse(g.isAdjacent(2, 0));
        ArrayCoordinate point2 = new ArrayCoordinate(3, 2);
        g.setPreviousButton(point2);
        assertTrue(g.isAdjacent(3, 2));
        assertTrue(g.isAdjacent(3, 1));
        assertTrue(g.isAdjacent(2,2));
    }

    @Test
    public void testIsCorrect()
    {
        Grid grid = new Grid("Easy");
        grid.squares[4][0] = true;
        assertTrue(grid.isCorrect(4, 0));
        grid.squares[3][0] = false;
        assertFalse(grid.isCorrect(3,0));
    }

    @Test
    public void testReset()
    {
        Grid grid = new Grid("Easy");
        grid.reset();
        assertEquals(0, grid.getPrevCol());
        assertEquals(grid.getSize() - 1, grid.getPrevRow()); 
    }

    @Test
    public void testinitGrid()
    {
        Grid easyGrid = new Grid("Easy");
        assertEquals(5, easyGrid.getSize());
        Grid mediumGrid = new Grid("Medium");
        assertEquals(7, mediumGrid.getSize());
        Grid hardGrid = new Grid("Hard");
        assertEquals(10, hardGrid.getSize());
    }
}

