/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pathfinder;

import pathfinder.controller.GameController;
import pathfinder.model.Grid;
import pathfinder.view.ErrorMessage;
import pathfinder.view.LevelSelectionGUI;
import pathfinder.view.PathfinderGUI;
import pathfinder.model.*;

public class App {
    public static void main(String[] args) {
        GameController controller = new GameController();
    }
}
